### ISSUE TITLE
Access the code inside the editor

### ISSUE THREAD

**Issue by elsvene** [joeskeen/reveal-monaco#3]
What is the proper way to programmatically access the code inside the editor? (Use Case: I want to put the edited code in an IFrame in order to render it as a kind of preview.)

I tried simple DOM API such as:

`document.querySelector(".monaco").textContent`

but it also contains e.g. the line numbers.

I only found a way by extending the plugin so that it attaches the `activeEditor`to the `codeBlock` (see attached `plugin.js` line 110 along with the attached reveal test case).

Is there a better way to access editor content?

[activeEditor-hack.zip](https://github.com/joeskeen/reveal-monaco/files/13601396/activeEditor-hack.zip)

**Comment by joeskeen** [comment]
Hey @elsvene thanks for being interested in and looking at this project! I don't spend a lot of time on this and I get a ton of GitHub notifications that slip between the cracks, so I'm glad I saw this when I did!

I know that the Monaco editor object itself has a .value or .getValue() you can use to get the value from it (I've done this on other projects using Monaco). As far as exposing that through the plugin, that shouldn't be too hard (in theory). The challenge comes when you have multiple Monaco editors in your slide deck, what would be the best way to get a specific instance?

Also, if I remember properly (as I haven't been deep in the code for a while), for performance reasons the monaco editor is unloaded after you leave the slide it's on.

Can you tell me a little more about your use case and what you would like to accomplish, so I can provide more help?

**Comment by elsvene** [comment]
Hi @joeskeen, thanks for your quick reply. My goal is a slide that allows editing code in the editor (e.g. an HTML site) and then rendering the edited code on the same slide after pushing a button.

I built and attached an extended test case that shows what I try to achieve:
[activeEditor-hack-extended.zip](https://github.com/joeskeen/reveal-monaco/files/13624179/activeEditor-hack-extended.zip)

It kind of works, but I had to extend the plugin in a way that feels "hacky" to me. You can see the line I added to the plugin in [this commit](https://github.com/elsvene/reveal-monaco/commit/9afe37e33c9130396640f37606103894e8757f12).

It even seems to work with multiple slides, but I wonder whether there is a better way to access the editor contents.

**Comment by joeskeen** [comment]
Yeah I see what you mean by a "hacky" solution. Putting arbitrary data onto a DOM element doesn't seem like the best solution, even though it's an easy one ;) 

I'm wondering if we could have the plugin emit events for data change, then your code outside the plugin could subscribe to them. (thought of this when reviewing the RevealJS docs here: https://revealjs.com/postmessage/). That way you could keep the variable populated via event callback and when the button is pressed you could just use the value.

The `this.activeEditor` variable is of this type: https://microsoft.github.io/monaco-editor/docs.html#interfaces/editor.IStandaloneCodeEditor.html

I think this would only require a small amount of code around where you made the change. Maybe something like this? (warning: untested):

```js
this.activeEditor.getModel().onDidChangeContent(e => {
  const contentChangeEvent = new CustomEvent("reveal-monaco-content-change", { detail: { textContent: this.activeEditor.getModel().getValue() } });
  window.dispatchEvent(contentChangeEvent);
})
```

What do you think of that approach?

**Comment by elsvene** [comment]
I think that is a very clean solution as it's more loosely coupled and less "arbitrary" than my hack!

I tested the code on my example and it works great. However, I also required an initial event in order retrieve the intial code value before any editing (e.g., press the button without changing the displayed code):

```javascript
this.activeEditor.getModel().onDidChangeContent(e => {
  const contentChangeEvent = new CustomEvent("reveal-monaco-content-change", { detail: { textContent: this.activeEditor.getModel().getValue() } });
  window.dispatchEvent(contentChangeEvent);
});

window.dispatchEvent(new CustomEvent("reveal-monaco-content-initialized", { detail: { textContent: this.activeEditor.getModel().getValue() } }));
```

You can also see the code in [this branch](https://github.com/elsvene/reveal-monaco/blob/editorAccess/plugin.js).

Here is my test case with the updated code:
[contentChangeEvents.zip](https://github.com/joeskeen/reveal-monaco/files/13627608/contentChangeEvents.zip)

**Comment by joeskeen** [comment]
That would work. I'm also fine with calling the Content Changed event when you first initialize it as well.

**Comment by elsvene** [comment]
Feature added with PR #4.
